name: Deploy Main Branch to Hostinger (TrustJobs)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Main Branch
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, ctype, json, tokenizer, curl, pdo_mysql
          coverage: none

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      # Step 4: Install Node.js and build assets
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 5: Install npm dependencies and build assets
      - name: Install npm dependencies and build
        run: |
          npm ci
          npm run build

      # Step 6: Install sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync

      # Step 7: Deploy to Hostinger
      - name: Deploy to Hostinger
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          DEPLOY_DIR="/home/u367101322/domains/jobtrust.space/public_html"
          
          # Copy files using rsync
          sshpass -p "$FTP_PASSWORD" rsync -avz \
            --exclude '.env' \
            --exclude '.htaccess' \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude 'vendor' \
            --exclude 'storage/logs/*' \
            --exclude 'storage/framework/cache/*' \
            --exclude 'storage/framework/sessions/*' \
            --exclude 'storage/framework/views/*' \
            --exclude 'tests' \
            --exclude 'README.md' \
            --exclude 'DEPLOYMENT_GUIDE.md' \
            --exclude '.github' \
            -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:"$DEPLOY_DIR"

      # Step 8: Set permissions
      - name: Set permissions
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && chmod -R 755 storage bootstrap/cache"

      # Step 9: Run migrations
      - name: Run migrations
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && php artisan migrate --force"

      # Step 10: Check and run seeders
      - name: Check and run seeders
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && php artisan db:seed --force"

      # Step 11: Optimize Laravel
      - name: Optimize Laravel
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache"

      # Step 12: Create storage link
      - name: Create storage link
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && php artisan storage:link"

      # Step 13: Verify deployment
      - name: Verify deployment
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd /home/u367101322/domains/jobtrust.space/public_html && php artisan --version"
